name: text_qoute
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  cloud_firestore:
  cupertino_icons:
  dartz:
  path_provider:
  flutter_bloc:
  hydrated_bloc:
  provider:
  shared_preferences:
  flutter_svg:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter Import Modules and Assets

flutter:
  assets:
    - assets/vectors/logo.png
    - assets/vectors/logo2.png
    - assets/vectors/Logo.svg



  uses-material-design: true

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
