// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4P_YCG70toftJhO_rOtEEylf4tJYBG78',
    appId: '1:596959164328:web:120644fae4c7892d9f0f9d',
    messagingSenderId: '596959164328',
    projectId: 'bionic-store-303613',
    authDomain: 'bionic-store-303613.firebaseapp.com',
    storageBucket: 'bionic-store-303613.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ2PkW5et5Y-t8l8zTkLS3oKFj5HdAems',
    appId: '1:596959164328:android:92eff6f16924d9a09f0f9d',
    messagingSenderId: '596959164328',
    projectId: 'bionic-store-303613',
    storageBucket: 'bionic-store-303613.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1lip0ltRy7GubI-pQe5zoJ8CnFnew0Bg',
    appId: '1:596959164328:ios:52b69e59fca423a29f0f9d',
    messagingSenderId: '596959164328',
    projectId: 'bionic-store-303613',
    storageBucket: 'bionic-store-303613.firebasestorage.app',
    iosBundleId: 'com.example.textQoute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1lip0ltRy7GubI-pQe5zoJ8CnFnew0Bg',
    appId: '1:596959164328:ios:52b69e59fca423a29f0f9d',
    messagingSenderId: '596959164328',
    projectId: 'bionic-store-303613',
    storageBucket: 'bionic-store-303613.firebasestorage.app',
    iosBundleId: 'com.example.textQoute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4P_YCG70toftJhO_rOtEEylf4tJYBG78',
    appId: '1:596959164328:web:23fdebbb0850301c9f0f9d',
    messagingSenderId: '596959164328',
    projectId: 'bionic-store-303613',
    authDomain: 'bionic-store-303613.firebaseapp.com',
    storageBucket: 'bionic-store-303613.firebasestorage.app',
  );
}
